import { Doula } from '../types/doula';

export const mockDoulas: Doula[] = [
  {
    id: '1',
    name: 'Riley Johnston',
    imageUrl: '/riley_johnston.png',
    type: 'Postpartum',
    zipCode: '98102',
    city: 'Bellevue',
    state: 'WA',
    rating: 5.0,
    reviewCount: 25,
    priceRange: '$1.00',
    bio: 'Dedicated postpartum doula specializing in trauma-informed care and physical/emotional recovery during the critical fourth trimester.',
    availableDates: ['2026-06-28', '2026-06-30', '2026-07-05', '2026-07-15'],
    pronouns: 'she/her',
    testimonialsCount: 25,
    tags: ['Postpartum Doula', 'Trauma-informed', 'Birth Doula', 'LGBTQ+ clients', 'First time parents', 'Overnight support', 'Lactation support', 'Sibling integration', 'Spanish speaker', 'IVF support'],
    packagesStartAt: 1.00,
    addOnServicesStartAt: 35,
    hasSlidingScale: false,
    hasPaymentPlans: false,
    hasRosetteBadge: false,
    availableDays: ['Monday', 'Wednesday', 'Saturday'],
    careOffered: ['Overnight support', 'Sibling support'],
    certifications: ['DONA International'],
    inclusiveCare: ['LGBTQ+ Friendly', 'Single Parent Support'],
    specialCircumstances: ['VBAC Support'],
    supportTypes: ['Emotional support', 'Partner support'],
    languages: ['English', 'Spanish']
  },
  {
    id: '2',
    name: 'Jordan Lee',
    imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&h=300&fit=crop&crop=face',
    type: 'Postpartum',
    zipCode: '98102',
    city: 'Seattle',
    state: 'WA',
    rating: 4.9,
    reviewCount: 15,
    priceRange: '$1,000',
    bio: 'Supportive postpartum and birth doula offering inclusive, non-judgmental guidance for all family structures.',
    availableDates: ['2026-06-28', '2026-07-01', '2026-07-10'],
    pronouns: 'she/they',
    testimonialsCount: 15,
    tags: ['Postpartum Doula', 'Lactation consultation', 'LGBTQ+ Friendly', 'First time parents'],
    packagesStartAt: 1000,
    addOnServicesStartAt: 40,
    hasSlidingScale: false,
    hasPaymentPlans: false,
    hasRosetteBadge: false,
    availableDays: ['Tuesday', 'Thursday', 'Sunday'],
    careOffered: ['Overnight support', 'Lactation consultation'],
    certifications: ['CAPPA Certified'],
    inclusiveCare: ['LGBTQ+ Friendly', 'Teen Parent Support'],
    specialCircumstances: ['Twins/Multiples'],
    supportTypes: ['Physical comfort', 'Evidence-based info'],
    languages: ['English', 'French']
  },
  {
    id: '3',
    name: 'Alex Rivera',
    imageUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=300&h=300&fit=crop&crop=face',
    type: 'Birth',
    zipCode: '98102',
    city: 'Bellevue',
    state: 'WA',
    rating: 4.8,
    reviewCount: 10,
    priceRange: '$800',
    bio: 'Compassionate birth doula dedicated to providing evidence-based labor positioning and gentle advocacy support.',
    availableDates: ['2026-06-29', '2026-07-04', '2026-07-18'],
    pronouns: 'she/her',
    testimonialsCount: 10,
    tags: ['Birth Doula', 'Antepartum support', 'High-risk Pregnancy', 'Single parents'],
    packagesStartAt: 800,
    addOnServicesStartAt: 30,
    hasSlidingScale: false,
    hasPaymentPlans: true,
    hasRosetteBadge: true,
    availableDays: ['Monday', 'Friday', 'Saturday'],
    careOffered: ['Antepartum support', 'Lactation consultation'],
    certifications: ['ICEA Certified'],
    inclusiveCare: ['Single Parent Support', 'Surrogacy & Adoption'],
    specialCircumstances: ['High-risk Pregnancy', 'IVF Support'],
    supportTypes: ['Physical comfort', 'Emotional support'],
    languages: ['English', 'Spanish', 'American Sign Language']
  },
  {
    id: '4',
    name: 'Sam Taylor',
    imageUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=300&h=300&fit=crop&crop=face',
    type: 'Full Spectrum',
    zipCode: '98102',
    city: 'Redmond',
    state: 'WA',
    rating: 5.0,
    reviewCount: 8,
    priceRange: '$600',
    bio: 'Newly certified full spectrum doula passionate about providing high quality physical, emotional, and educational support.',
    availableDates: ['2026-07-02', '2026-07-12', '2026-07-25'],
    pronouns: 'she/they',
    badgeText: 'New to Aunti',
    testimonialsCount: 8,
    tags: ['Full Spectrum', 'Antepartum support', 'Twins/Multiples', 'IVF support'],
    packagesStartAt: 600,
    addOnServicesStartAt: 45,
    hasSlidingScale: false,
    hasPaymentPlans: true,
    hasRosetteBadge: true,
    availableDays: ['Wednesday', 'Thursday', 'Friday'],
    careOffered: ['Antepartum support', 'Sibling support'],
    certifications: ['ProDoula Certified'],
    inclusiveCare: ['Teen Parent Support', 'Surrogacy & Adoption'],
    specialCircumstances: ['Twins/Multiples', 'IVF Support'],
    supportTypes: ['Partner support', 'Evidence-based info'],
    languages: ['English', 'Chinese']
  },
  {
    id: '5',
    name: 'Maria Santos',
    imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&h=300&fit=crop&crop=face',
    type: 'Birth',
    zipCode: '98102',
    city: 'Seattle',
    state: 'WA',
    rating: 4.7,
    reviewCount: 18,
    priceRange: '$1,500',
    bio: 'Experienced bilingual birth doula specializing in physiological birth and continuous physical and partner support.',
    availableDates: ['2026-06-27', '2026-06-28', '2026-07-05'],
    pronouns: 'she/her',
    testimonialsCount: 18,
    tags: ['Birth Doula', 'Bilingual', 'VBAC Support', 'Partner support'],
    packagesStartAt: 1500,
    addOnServicesStartAt: 50,
    hasSlidingScale: true,
    hasPaymentPlans: true,
    hasRosetteBadge: true,
    availableDays: ['Monday', 'Tuesday', 'Sunday'],
    careOffered: ['Antepartum support', 'Overnight support'],
    certifications: ['DONA International'],
    inclusiveCare: ['LGBTQ+ Friendly', 'Surrogacy & Adoption'],
    specialCircumstances: ['VBAC Support', 'High-risk Pregnancy'],
    supportTypes: ['Physical comfort', 'Partner support'],
    languages: ['English', 'Spanish']
  },
  {
    id: '6',
    name: 'Chloe Dubois',
    imageUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=300&h=300&fit=crop&crop=face',
    type: 'Postpartum',
    zipCode: '98102',
    city: 'Kirkland',
    state: 'WA',
    rating: 4.6,
    reviewCount: 9,
    priceRange: '$900',
    bio: 'Compassionate care for the postpartum period focusing on sibling integration, parent recovery, and breastfeeding assistance.',
    availableDates: ['2026-06-30', '2026-07-03', '2026-07-10'],
    pronouns: 'she/her',
    testimonialsCount: 9,
    tags: ['Postpartum Doula', 'Lactation consultation', 'Sibling support', 'French speaker'],
    packagesStartAt: 900,
    addOnServicesStartAt: 35,
    hasSlidingScale: true,
    hasPaymentPlans: false,
    hasRosetteBadge: false,
    availableDays: ['Tuesday', 'Wednesday', 'Thursday'],
    careOffered: ['Lactation consultation', 'Sibling support'],
    certifications: ['CAPPA Certified'],
    inclusiveCare: ['Single Parent Support', 'Teen Parent Support'],
    specialCircumstances: ['IVF Support', 'Twins/Multiples'],
    supportTypes: ['Emotional support', 'Evidence-based info'],
    languages: ['English', 'French']
  },
  {
    id: '7',
    name: 'Elena Rostova',
    imageUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=300&h=300&fit=crop&crop=face',
    type: 'Full Spectrum',
    zipCode: '98102',
    city: 'Renton',
    state: 'WA',
    rating: 4.9,
    reviewCount: 22,
    priceRange: '$2,000',
    bio: 'Dedicated advocate and full spectrum support provider focusing on evidence-based guidance and trauma-informed physical comfort.',
    availableDates: ['2026-06-28', '2026-07-08', '2026-07-20'],
    pronouns: 'she/her',
    testimonialsCount: 22,
    tags: ['Full Spectrum', 'Trauma-informed', 'High-risk Pregnancy', 'ASL friendly'],
    packagesStartAt: 2000,
    addOnServicesStartAt: 60,
    hasSlidingScale: false,
    hasPaymentPlans: true,
    hasRosetteBadge: true,
    availableDays: ['Monday', 'Wednesday', 'Friday', 'Sunday'],
    careOffered: ['Overnight support', 'Antepartum support'],
    certifications: ['ICEA Certified'],
    inclusiveCare: ['LGBTQ+ Friendly', 'Single Parent Support'],
    specialCircumstances: ['High-risk Pregnancy', 'VBAC Support'],
    supportTypes: ['Physical comfort', 'Evidence-based info'],
    languages: ['English', 'American Sign Language']
  },
  {
    id: '8',
    name: 'Mei-Ling Chen',
    imageUrl: 'https://images.unsplash.com/photo-1554784790-3349b763876e?w=300&h=300&fit=crop&crop=face',
    type: 'Birth',
    zipCode: '98102',
    city: 'Seattle',
    state: 'WA',
    rating: 4.8,
    reviewCount: 14,
    priceRange: '$1,100',
    bio: 'Providing gentle and experienced birth support, specialized lactation help, and partner-inclusive labor coaching.',
    availableDates: ['2026-06-29', '2026-07-07', '2026-07-15'],
    pronouns: 'she/her',
    testimonialsCount: 14,
    tags: ['Birth Doula', 'Lactation consultation', 'Partner support', 'Chinese speaker'],
    packagesStartAt: 1100,
    addOnServicesStartAt: 40,
    hasSlidingScale: false,
    hasPaymentPlans: false,
    hasRosetteBadge: false,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Friday'],
    careOffered: ['Lactation consultation', 'Sibling support'],
    certifications: ['ProDoula Certified'],
    inclusiveCare: ['LGBTQ+ Friendly', 'Surrogacy & Adoption'],
    specialCircumstances: ['Twins/Multiples', 'High-risk Pregnancy'],
    supportTypes: ['Emotional support', 'Partner support'],
    languages: ['English', 'Chinese']
  }
];
